package msk.rest.vio.emu.domain

enum class VioDocType(val id: Int, val docType: DocumentTypeClassifier, val docKind: DocumentKind) {
    MZMK(1013, DocumentTypeClassifier.MZMK, DocumentKind.APPLICATION),
    MZVD(1016, DocumentTypeClassifier.MZVD, DocumentKind.APPLICATION),
    MZRK(1011, DocumentTypeClassifier.MZRK, DocumentKind.APPLICATION),
    MZPM(40101, DocumentTypeClassifier.MZPM, DocumentKind.APPLICATION),
    MZAZ(1023, DocumentTypeClassifier.MZAZ, DocumentKind.APPLICATION),
    MZOB(1024, DocumentTypeClassifier.MZOB, DocumentKind.APPLICATION),
    MZOP(1021, DocumentTypeClassifier.MZOP, DocumentKind.APPLICATION),
    MZEV(1033, DocumentTypeClassifier.MZEV, DocumentKind.APPLICATION),
    MKAD(1017, DocumentTypeClassifier.MKAD, DocumentKind.APPLICATION),
    MZZD(1050, DocumentTypeClassifier.MZZD, DocumentKind.APPLICATION), //todo Нужен код НСИ
    ES(12, DocumentTypeClassifier.ES, DocumentKind.APPLICATION),
    MZPEV(80085, DocumentTypeClassifier.MZPEV, DocumentKind.APPLICATION),
    MZOS(40054, DocumentTypeClassifier.MZOS, DocumentKind.APPLICATION),
    MZOV(40133, DocumentTypeClassifier.MZOV, DocumentKind.APPLICATION),
    SZI_SPU(380, DocumentTypeClassifier.SZI_SPU, DocumentKind.APPLICATION),
    MZUR(80161, DocumentTypeClassifier.MZUR, DocumentKind.APPLICATION),
    MUBZ(80081, DocumentTypeClassifier.MUBZ, DocumentKind.APPLICATION),
    ZPNP(80156, DocumentTypeClassifier.ZPNP, DocumentKind.APPLICATION),

    VMSE(30002, DocumentTypeClassifier.VMSE, DocumentKind.REQUEST),
    MOMV1(40072, DocumentTypeClassifier.MOMV1, DocumentKind.REQUEST),
    MOMV2(40073, DocumentTypeClassifier.MOMV2, DocumentKind.REQUEST),
    MORO1(40078, DocumentTypeClassifier.MORO1, DocumentKind.REQUEST),
    MORO2(40079, DocumentTypeClassifier.MORO2, DocumentKind.REQUEST),
    MOZG1(40096, DocumentTypeClassifier.MOZG1, DocumentKind.REQUEST),
    MOZG2(40097, DocumentTypeClassifier.MOZG2, DocumentKind.REQUEST),
    MOZG3(40098, DocumentTypeClassifier.MOZG3, DocumentKind.REQUEST),
    MOZG4(40099, DocumentTypeClassifier.MOZG4, DocumentKind.REQUEST),
    MOZG5(40100, DocumentTypeClassifier.MOZG5, DocumentKind.REQUEST),
    MOOM1(40083, DocumentTypeClassifier.MOOM1, DocumentKind.REQUEST),
    MOOM2(40084, DocumentTypeClassifier.MOOM2, DocumentKind.REQUEST),
    MOMV3(40074, DocumentTypeClassifier.MOMV3, DocumentKind.REQUEST),
    MOZAG(40076, DocumentTypeClassifier.MOZAG, DocumentKind.REQUEST),
    MSUR(40086, DocumentTypeClassifier.MSUR, DocumentKind.REQUEST),
    MOZ12(40115, DocumentTypeClassifier.MOZ12, DocumentKind.REQUEST),
    MOZ22(40116, DocumentTypeClassifier.MOZ22, DocumentKind.REQUEST),
    MOZ32(40117, DocumentTypeClassifier.MOZ32, DocumentKind.REQUEST),
    MOZ42(40118, DocumentTypeClassifier.MOZ42, DocumentKind.REQUEST),
    MOZ52(40119, DocumentTypeClassifier.MOZ52, DocumentKind.REQUEST),
    MOMSZ(353, DocumentTypeClassifier.MOMSZ, DocumentKind.REQUEST),
    MORR1(40080, DocumentTypeClassifier.MORR1, DocumentKind.REQUEST);
}